name: Latest blog post workflow
on:
  schedule:
    # Runs at 6:15 AM every Monday
    - cron: '15 6 * * 1'
  workflow_dispatch:

jobs:
  update-readme-with-blog:
    name: Update this repo's README with latest blog posts
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: gautamkrishnar/blog-post-workflow@master
        with:
          max_post_count: "5"
          feed_list: "https://medium.com/feed/@anlishamaharjan"
